Feature/add custom registration instructions
pxblue/react-workflows pull request #30
Opened 2021-03-24 12:50 UTC by jeffvg

#### Changes proposed in this Pull Request:
- pass in custom account details
- update invite and self reg
- 

#### Screenshots:

2021-03-24 17:33 UTC, joebochill reviewed
Excellent job! 

If we want to avoid users having to remember to put a margin at the top of their first custom form (and also handle the responsive change from 32 to 24px), we can do a little refactoring of the first account details page to:
- move the AccountDetailsWrapper to wrap both the built in and custom forms
- use the predefined class to handle the dynamic margins between the two form

it would look more like:

```tsx
        {
            name: 'AccountDetails',
            pageTitle: t('REGISTRATION.STEPS.ACCOUNT_DETAILS'),
            pageBody: (
                <AccountDetailsWrapper>
                    <AccountDetailsScreen
                        ...
                    />
                    {FirstCustomPage && (
                        <div className={sharedClasses.textField}>
                            <FirstCustomPage ...  />
                        </div>
                    )}
                </AccountDetailsWrapper>
            ),
        },
```

that would also necessitate simplifying the AccountDetails component to remove the `<AccountDetailsWrapper>` there (and replace it with a React Fragment `</>`) since we moved it into the pagers instead:
```tsx
    return (
        <>
            <TextField ...  />
            <TextField ... />
        </>
    );
```

2021-03-24 17:33 UTC, joebochill commented on login-workflow/src/screens/InviteRegistrationPager.tsx
>                  //@ts-ignore
You might be able to remove this ts ignore now...if not add a comment to explain why we had to leave it in:

```
// @ts-ignore there won't be any nulls after we filter them
```

2021-03-24 17:33 UTC, joebochill commented on login-workflow/src/screens/SelfRegistrationPager.tsx
>                  //@ts-ignore
See my other comment about the ts-ignores and if we can remove them now

2021-03-24 17:33 UTC, joebochill commented on login-workflow/example/src/components/CustomDetailsScreen.tsx
> +                style={{ marginTop: '32px' }}
See my suggestion above that will eliminate the need for users to have to manually add these margins

2021-03-24 17:33 UTC, joebochill commented
Oh, and can you comment out the custom pages at checkin so a fresh clone will always start with the basic bare-bones workflow.

2021-03-24 19:02 UTC, jeffvg commented
> Excellent job!
> 
> If we want to avoid users having to remember to put a margin at the top of their first custom form (and also handle the responsive change from 32 to 24px), we can do a little refactoring of the first account details page to:
> 
> * move the AccountDetailsWrapper to wrap both the built in and custom forms
> * use the predefined class to handle the dynamic margins between the two form
> 
> it would look more like:
> 
> ```tsx
>         {
>             name: 'AccountDetails',
>             pageTitle: t('REGISTRATION.STEPS.ACCOUNT_DETAILS'),
>             pageBody: (
>                 <AccountDetailsWrapper>
>                     <AccountDetailsScreen
>                         ...
>                     />
>                     {FirstCustomPage && (
>                         <div className={sharedClasses.textField}>
>                             <FirstCustomPage ...  />
>                         </div>
>                     )}
>                 </AccountDetailsWrapper>
>             ),
>         },
> ```
> 
> that would also necessitate simplifying the AccountDetails component to remove the `<AccountDetailsWrapper>` there (and replace it with a React Fragment `</>`) since we moved it into the pagers instead:
> 
> ```tsx
>     return (
>         <>
>             <TextField ...  />
>             <TextField ... />
>         </>
>     );
> ```

Change here? 
and what about onDetailsChanged={setAccountDetails}
                        initialDetails={accountDetails}
                        onSubmit={

![image](https://user-images.githubusercontent.com/37150565/112368759-cd83d080-8cb1-11eb-9ef6-a3d0a93f64cd.png)

2021-03-25 18:52 UTC, joebochill approved these changes

2021-03-25 18:54 UTC, joebochill requested changes
One last thing...you need to update the docs for registration customization (https://github.com/pxblue/react-workflows/blob/feature/add-custom-registration-instructions/login-workflow/docs/customization.md#registration-details). You can pretty much copy right from the changes in the RN workflow:

https://github.com/pxblue/react-native-workflows/blob/dev/login-workflow/docs/customization.md#registration-details

2021-03-25 21:54 UTC, joebochill approved these changes

2021-03-25 21:54 UTC, merged